In [35]:
import pandas as pd
new_data = pd.DataFrame(new_features, columns=X_train.columns)

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier



In [9]:
data = pd.read_csv("/content/Sleep_Data_Sampledremoved_Dis.csv")

In [10]:
X = data.iloc[:, :-1]  # Features
y = data.iloc[:, -1]   # Sleep_Quality (target)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  Index(['Person ID', 'Age', 'Sleep Duration', 'Physical Activity Level',
       'Stress Level', 'Heart Rate', 'Daily Steps'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['Gender', 'Occupation', 'BMI Category', 'Blood Pressure'], dtype='object'))])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [15]:
y_pred = model.predict(X_test)

In [24]:
print("Model Evaluation:")
print("-----------------")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")


Model Evaluation:
-----------------
Accuracy: 0.9937


In [25]:
print("Model Evaluation:")
print("-----------------")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Model Evaluation:
-----------------
Accuracy: 0.9937

Classification Report:
              precision    recall  f1-score   support

           4       1.00      0.78      0.88         9
           5       0.95      0.98      0.97        62
           6       0.99      1.00      1.00      1044
           7       1.00      0.98      0.99       508
           8       0.99      1.00      1.00      1172
           9       1.00      1.00      1.00       205

    accuracy                           0.99      3000
   macro avg       0.99      0.96      0.97      3000
weighted avg       0.99      0.99      0.99      3000


Confusion Matrix:
[[   7    2    0    0    0    0]
 [   0   61    1    0    0    0]
 [   0    1 1041    1    1    0]
 [   0    0    6  496    6    0]
 [   0    0    0    1 1171    0]
 [   0    0    0    0    0  205]]


In [26]:
if hasattr(model.named_steps['classifier'], 'feature_importances_'):
    # Get feature names after one-hot encoding
    cat_encoder = model.named_steps['preprocessor'].named_transformers_['cat']
    cat_features = cat_encoder.get_feature_names_out(categorical_cols)
    all_features = np.concatenate([numerical_cols, cat_features])


In [37]:
new_features = [[11294, 'Male', 42, 'Lawyer', 7.10, 68, 4, 'Normal', '135/90', 68, 7000]]
predicted_sleep_quality = model.predict(new_data)
print("Predicted Sleep Quality:", predicted_sleep_quality[0])

Predicted Sleep Quality: 8


In [7]:
X_train.head()

Person ID  Gender  Age         Occupation  Sleep Duration  \
9839        9840    Male   44        Salesperson            6.40   
9680        9681  Female   54              Nurse            7.10   
7093        7094  Female   54              Nurse            7.05   
11293      11294    Male   42             Lawyer            7.10   
820          821    Male   44  Software Engineer            7.95   

       Physical Activity Level  Stress Level BMI Category Blood Pressure  \
9839                        45             7   Overweight         130/85   
9680                        82             6   Overweight         140/95   
7093                        82             6   Overweight         140/95   
11293                       68             4       Normal         135/90   
820                         45             4       Normal         120/80   

       Heart Rate  Daily Steps  
9839           72         6000  
9680           72         8500  
7093           72         8500  
11293          68         7000  
820            68         6500

In [6]:
y_train.head()

9839     6
9680     8
7093     8
11293    8
820      8
Name: Quality of Sleep, dtype: int64