<a href="https://colab.research.google.com/github/ne-adrita/Predicting-Sleep-Quality-through-Behavioral-Pattern-Recognition/blob/main/KNN_up.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 🧠 KNN Regression and Classification on Sleep Dataset

# 📌 Step 1: Import Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score,
    accuracy_score, classification_report, confusion_matrix
)

# 📂 Step 2: Load and Clean Dataset
df = pd.read_csv('Sleep_Data_Sampled(missing_Dis).csv')
df.drop(columns=['Person ID'], inplace=True)

# Label Encode Categorical Columns
categorical_cols = ['Gender', 'Occupation', 'BMI Category', 'Blood Pressure']
for col in categorical_cols:
    df[col] = LabelEncoder().fit_transform(df[col])

# 🎯 Step 3: Define Features and Targets
X = df.drop(columns=['Quality of Sleep'])
y_reg = df['Quality of Sleep']
y_class = y_reg.apply(lambda x: 0 if x <= 4 else (1 if x <= 7 else 2))  # Classification target

# ⚖ Step 4: Feature Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 🔀 Step 5: Train/Test Split
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_scaled, y_reg, test_size=0.2, random_state=42)
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_scaled, y_class, test_size=0.2, random_state=42)

# 🟢 Step 6A: KNN Regression
regressor = KNeighborsRegressor(n_neighbors=5)
regressor.fit(X_train_r, y_train_r)
y_pred_r = regressor.predict(X_test_r)

print("📊 Regression Evaluation (KNN)")
print("MAE:", mean_absolute_error(y_test_r, y_pred_r))
print("MSE:", mean_squared_error(y_test_r, y_pred_r))
print("R² Score:", r2_score(y_test_r, y_pred_r))

# 🟢 Step 6B: KNN Classification
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train_c, y_train_c)
y_pred_c = classifier.predict(X_test_c)

print("\n📊 Classification Evaluation (KNN)")
print("Accuracy:", accuracy_score(y_test_c, y_pred_c))
print("Confusion Matrix:\n", confusion_matrix(y_test_c, y_pred_c))
print("Classification Report:\n", classification_report(y_test_c, y_pred_c, target_names=["Poor", "Average", "Good"]))


📊 Regression Evaluation (KNN)
MAE: 0.031866666666666675
MSE: 0.020106666666666665
R² Score: 0.9818043442128191

📊 Classification Evaluation (KNN)
Accuracy: 0.9903333333333333
Confusion Matrix:
 [[   7    2    0]
 [   0 1598   16]
 [   0   11 1366]]
Classification Report:
               precision    recall  f1-score   support

        Poor       1.00      0.78      0.88         9
     Average       0.99      0.99      0.99      1614
        Good       0.99      0.99      0.99      1377

    accuracy                           0.99      3000
   macro avg       0.99      0.92      0.95      3000
weighted avg       0.99      0.99      0.99      3000

